#!/bin/bash

#echo "The name of the file is: $0 and it is going to be self-deleted."

#rm -f $0

# ran the script correctly, but i dont want to delete the file 
#so the script has been commented out

